### ISSUE TITLE
Two feature suggestions

### ISSUE THREAD

**Issue by ghost** [quanganhquanganh/Anki-Youtube-Audio-Miner#3]
Hey!
So there's this similar addon `https://ankiweb.net/shared/info/1023383878`
which also parses the related subtitle part. Is this doable with your addon?
Have a great day :)

**Comment by quanganhquanganh** [comment]
Oh yeah totally. It's doable and needs only a couple of tweaks because pretty sure my code is very similar to that lol. But my add-on has a different goal in mind, so I intend to add more features relating to that goal then actually make an srs generator like that one. But who knows lol.

Sorry for the late reply again haha.
